### ISSUE TITLE
App crashes on deletion

### ISSUE THREAD

**Issue by talkingkarthik** [jktdeals/Deals#40] opened 2016-03-19 23:03 UTC
Below is the stach trace. 

03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{3c198f4d position=1 id=-1, oldPos=1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4499)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4630)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4611)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:2977)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2901)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.View.layout(View.java:15671)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5038)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
03-19 19:02:34.023 9483-9483/com.jktdeals.deals E/AndroidRuntime:   at android.os.Handl

**Comment by talkingkarthik** [comment] 2016-03-19 23:04
Hi Tane, 

Choreographer is on stack, did you try to animate something upon deletion of the deal ?

**Comment by tachyonlabs** [comment] 2016-03-20 00:06
No, I haven't done anything with the delete yet, but I want to -- I think probably the adapter should be passing the click up to the fragment to handle, that there should be an "Are you sure?" question, and also previously delete had the problem that when you deleted a deal, instead of the other deals moving up in the list, the deleted position changed to display a duplicate of the deal below it. So I will see if I can get those things working next.

**Comment by tachyonlabs** [comment] 2016-03-20 02:04
I got delete working and scrolling up properly and will upload after I put in an "Are you sure?" dialog also.

**Comment by tachyonlabs** [comment] 2016-03-20 04:04
Fixed.

**Closed as completed by tachyonlabs** 2016-03-20 04:04 UTC
